name: 3603dphoto
channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.8
  - pip
  - cuda
  - tqdm
  - pip:
    - matplotlib
    - opencv-python
    - scipy
    - scikit-image
    - lpips
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.1+cu118
    - torchvision==0.15.2+cu118
    - torchaudio==2.0.2+cu118
    - torchmetrics==1.4.0
    - torch-fidelity
    - tensorboard
    - diffusers==0.29.0
    - transformers
    - accelerate
    - timm==0.6.7
